User:
  ribbon:
    eureka:
      enabled: false
    listOfServers: localhost:8087,localhost:8081,localhost:8082
    ServerListRefreshInterval: 15000

server:
  port: 8888

spring:
  main:
    allow-circular-references: true